import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from 'sonner'



const primaryFont = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-primary",
  weight: "100 900",
});
const secondaryFont = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-secondary",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E - commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={secondaryFont.className}>
      
      <body className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}>        
        <Navbar />
      <main className="container">{children}</main> 
        <Footer />
        <Toaster richColors position="top-center"/>
        
      </body>
      
    </html>
  );
}
